### ISSUE TITLE
WiFi & Bluetooth interrupts

### ISSUE THREAD

**Issue by MabezDev** [esp-rs/esp-pacs#25]
The peripheral sources for the WiFi & Bluetooth interrupts can be found in esp-idf, `components/soc/{CHIP}/interrupts.c`. The question is, how do we include these in our PACS? We don't have a peripheral to attach them to because the WiFi & Bluetooth stuff is private.

I don't like the idea of adding a dummy peripheral at all, people are inevitably going to try and use it as a real peripheral. What about adding the peripherals to a "system like" peripheral that already exists, e.g the interrupt controller (or DPORT on the esp32)?

**Comment by jessebraham** [comment]
For the `SW_INTR_*` interrupts on the ESP32-C3 I just added them to the `INTERRUPT_CORE0` peripheral due to lack of a better place. I also considered `SYSTEM` (or `DPORT` on the ESP32). Ultimately it doesn't matter where they end up as `svd2rust` just collects all interrupts into an enum anyways, but I agree that adding a dummy peripheral is not desirable.
